version: '3.8'

services:
  app:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/products_ada?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: products_ada
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
